### ISSUE TITLE
Resuemat Version 8126

### ISSUE THREAD

**Issue by ghost** [mwllgr/java-wtkcontrol#1]
Hallo, ich habe eine Resümat 8126 Version. Gibt es dafür auch eine address list? 

Für das FEHM modul gibt es ja anscheinend eine abgewandelte version. 

dort sind diese Adressen eingebunden. Leider is mir nicht klar wie ich das auf das file umsetzen muss.

Ich möchte die Infos in Influx DB schieben und da wäre das java modul von dir perfekt.

Danke

```
 'Versions-Nummer'        => { addr => 0x0000, bytes => 0x0002,                  unp => 'n' },
 'Temp-Aussen'            => { addr => 0x0008, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-Ruecklauf-Soll'    => { addr => 0x0014, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-Ruecklauf'         => { addr => 0x0018, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-Vorlauf'           => { addr => 0x001C, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-WW-Soll'           => { addr => 0x0020, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-WW'                => { addr => 0x0024, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-Raum'              => { addr => 0x0028, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-WQuelle-Ein'       => { addr => 0x0030, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-WQuelle-Aus'       => { addr => 0x0034, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-Verdampfer'        => { addr => 0x0038, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-Kondensator'       => { addr => 0x003C, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Temp-Saugleitung'       => { addr => 0x0040, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Druck-Verdampfer'       => { addr => 0x0048, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Druck-Kondensator'      => { addr => 0x004C, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Hzg-TempEinsatz'        => { addr => 0x00F4, bytes => 0x0004, fmat => '%0.1f', unp => 'f<', min => 15.0, max => 20.0 },
 'Hzg-TempBasisSoll'      => { addr => 0x00F8, bytes => 0x0004, fmat => '%0.1f', unp => 'f<', min => 20.0, max => 24.0 },
 'Hzg-KlSteilheit'        => { addr => 0x00FC, bytes => 0x0004, fmat => '%0.1f', unp => 'f<', min => 15.0, max => 30.0 },
 'Hzg-KlBegrenz'          => { addr => 0x0100, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Hzg-TempRlSoll'         => { addr => 0x0050, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Hzg-TempRlIst'          => { addr => 0x0054, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Hzg-TmpRaumSoll'        => { addr => 0x0105, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Hzg-RaumEinfluss'       => { addr => 0x0109, bytes => 0x0001,                  unp => 'C' },
 'Hzg-ExtAnhebung'        => { addr => 0x010A, bytes => 0x0004, fmat => '%0.1f', unp => 'f<', min => -5.0, max => 5.0 },
 'Hzg-Zeit-Ein'           => { addr => 0x010E, bytes => 0x0003, fmat => '%3$02d:%2$02d:%1$02d', unp => 'CCC'},
 'Hzg-Zeit-Aus'           => { addr => 0x0111, bytes => 0x0003, fmat => '%3$02d:%2$02d:%1$02d', unp => 'CCC' },
 'Hzg-AnhebungEin'        => { addr => 0x0114, bytes => 0x0003, fmat => '%3$02d:%2$02d:%1$02d', unp => 'CCC' },
 'Hzg-AnhebungAus'        => { addr => 0x0117, bytes => 0x0003, fmat => '%3$02d:%2$02d:%1$02d', unp => 'CCC' },
 'Hzg-St2Begrenz'         => { addr => 0x011A, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Hzg-Hysterese'          => { addr => 0x011E, bytes => 0x0004, fmat => '%0.1f', unp => 'f<', min => 1.0, max => 3.0  },
 'Hzg-PumpenNachl'        => { addr => 0x0122, bytes => 0x0001,                  unp => 'C',  min => 0,   max => 120  },
 'Klg-Abschaltung'        => { addr => 0x0123, bytes => 0x0001,                  unp => 'C' },
 'Klg-Temp-Einsatz'       => { addr => 0x0124, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Klg-TeBasisSoll'        => { addr => 0x0128, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Klg-KlSteilheit'        => { addr => 0x012C, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Klg-KlBegrenz'          => { addr => 0x0130, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Klg-KlSollwert'         => { addr => 0x0058, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Klg-Temp-Rl'            => { addr => 0x005C, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Ww-Abschaltung'         => { addr => 0x0134, bytes => 0x0001 },
 'Ww-Zeit-Ein'            => { addr => 0x0135, bytes => 0x0003, fmat => '%3$02d:%2$02d:%1$02d', unp => 'CCC' },
 'Ww-Zeit-Aus'            => { addr => 0x0138, bytes => 0x0003, fmat => '%3$02d:%2$02d:%1$02d', unp => 'CCC' },
 'Ww-Temp-Ist'            => { addr => 0x0060, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Ww-Temp-Soll'           => { addr => 0x013b, bytes => 0x0004, fmat => '%0.1f', unp => 'f<', min => 35, max => 55 },
 'Ww-Hysterese'           => { addr => 0x0143, bytes => 0x0004, fmat => '%0.1f', unp => 'f<', min => 5,  max => 10},
 'Uhrzeit'                => { addr => 0x0064, bytes => 0x0003, fmat => '%3$02d:%2$02d:%1$02d', unp => 'CCC' },
 'Datum'                  => { addr => 0x0067, bytes => 0x0003, fmat => '%02d.%02d.%02d', unp => 'CCC'},
 'BetrStundenKompressor'  => { addr => 0x006A, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'BetrStundenHzgPu'       => { addr => 0x006E, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'BetrStundenWwPu'        => { addr => 0x0072, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'BetrStundenSt2'         => { addr => 0x0076, bytes => 0x0004, fmat => '%0.1f', unp => 'f<' },
 'Zeit'                   => { addr => 0x0064, bytes => 0x0006, fmat=> '%4$02d.%5$02d.%6$02d %3$02d:%2$02d:%1$02d', unp => 'CCCCCC'},
 'SetBetriebsMode'        => { addr => 0x014E, bytes => 0x0003,                  unp => 'N', pack => 'xC*'},
 'Display-Zeile-1'        => { addr => 0x008E, bytes => 0x0002,                  unp => 'n' },
 'Display-Zeile-2'        => { addr => 0x0090, bytes => 0x0001,                  unp => 'C' },
 'Status-Gesamt'          => { addr => 0x00D2, bytes => 0x0001,                  unp => 'C' },
 'Status-Heizung'         => { addr => 0x00D4, bytes => 0x0003,                  unp => 'B24' },
 'Status-Kuehlung'        => { addr => 0x00DA, bytes => 0x0003,                  unp => 'B24' }, 
 'Mode-Heizung'           => { addr => 0x00DF, bytes => 0x0001,                  unp => 'B8' },
 'Mode-Kuehlung'          => { addr => 0x00E0, bytes => 0x0001,                  unp => 'B8' },
 'Mode-Warmwasser'        => { addr => 0x00E1, bytes => 0x0001,                  unp => 'B8' },
 'Heizung'                => { addr => 0x00DF, bytes => 0x0001,                  unp => 'b' },
 'Kuehlung'               => { addr => 0x00E0, bytes => 0x0001,                  unp => 'b' },
 'Warmwasser'             => { addr => 0x00E1, bytes => 0x0001,                  unp => 'b' }
```

**Comment by mwllgr** [comment]
Hallo @elektronikfreak!

Ganz gut "umschreiben" kannst du das ganze mit meiner FHEM-Variante für die 8011-Version.
Siehe dazu:

- https://github.com/mwllgr/fhem-waterkotte-resuemat-cd4/blob/master/FHEM/98_WKRCD4.pm#L164
- https://github.com/mwllgr/java-wtkcontrol/blob/master/address-list_version-7000-8000-8011.csv

Wenn du also zum Beispiel "BetrStundenKompressor" im Format für die Java-Variante haben willst, wäre das:
```csv
BetrStundenKompressor,6A,4,f,0,0,1
```

Wichtig ist, dass die csv-Datei in deinem Fall folgendermaßen beginnt:
```csv
Name,Menue,Addresse,Laenge,Typ,Min,Max,ReadOnly
BYTES,-.--,00,152,0,0,0,1
```

Wäre super, wenn du die fertig umgeschriebene CSV-Datei dann hier posten könntest, damit ich sie zum Projekt hinzufügen kann! :)

**Comment by ghost** [comment]
Hallo,

ich habe eine csv erstellt, leider klappt es nicht.

Der Time Sync funktioniert daher kann ich sehen das die Verbindung okay ist.
Wenn ich versuche Daten abzurufen sieht bleibt dein Tool ohne jegliche Informationen hängen. 

Ich muss es dann mit strg-c abbrechen.

Hier mal der Output mit eine –verbose ob es dir was bringt keine Ahnung: https://p.kll.li/?ba5216ce45bc014f#CRdKNUmohXDiMfeodNmQ54NcjvjYmWiuNJC2a1M1NiPh
Ich habe jetzt die Daten auf deinem Link verwendet. Glaubst Du das diese für die 8126 die richtigen sind.

Im Anhang auch die Datei, evtl. hast du ja auch die Möglichkeit und Lust diese kurz zu testen.

Vielen Dank und Gruß 
Oliver

**Comment by ghost** [comment]
Hallo nochmal,

ich habe die Aufschlüsselung der 8126 jetzt nochmal woanders gefunden.

https://forum.iobroker.net/topic/11059/script-hilfe-f%C3%BCr-abfrage-serielle-kommunikation-gesucht/7

Echt schräg, ich hatte das damals mal mit Ipsymcon in PHP realisiert und bekomme das jetzt nicht mehr hin.
Ich habe diese nun übertragen und denke das 511 Zeichen zurückkommen.  Siehe https://forum.iobroker.net/topic/11059/script-hilfe-f%C3%BCr-abfrage-serielle-kommunikation-gesucht/9

In der Datei habe ich also 1FF in der Bytes Zeile angegeben. Ob das so stimmt ist mir nicht klar.

Bei Typ habe ich immer f bei einer 4 Byte länge und bei allen anderen erstmal ein c. (gehe davon aus das dies Character heißen soll)

Anbei nun die neue Datei. Diese müsste eigentlich stimmen da ich diese früher auch schon in teilen verwendet hatte und auch in anderen Foren bzgl. der 8126 Version damit gearbeitet wird.

Wäre echt super wenn du da nochmal zeitfinden würdest und wir das Problem lösen könnten. Dann könntest du das auch noch in deinem FEHM Projekt übertragen. 

Oder läuft deine 8011 version definitiv auf der 8126 ?
Wenn ich dein Tool aufrufen passiert quasi nichts und es hängt. 

java -jar ./wtkcontrol-1.3.jar --no-gui --port /dev/ttyUSB0 --address-file address-list.csv

Vielen Dank

Gruß

**Comment by mwllgr** [comment]
Hallo Oliver,
hast du schon versucht, Befehle manuell an die Heizung zu senden, um zu sehen, welche Bytes als Antwort zurückkommen? Das Programm wartet nur, wenn keine richtige Antwort gemeldet wird.

Sei so gut und probier mal, manuell einen Lesebefehl (z.B. über PuTTY) zu senden und die erhaltenen Bytes hier rein zu schreiben.

**Comment by ghost** [comment]
Hallo,

ich habe das mit Hterm gemacht und `FF 10 02 01 15 00 00 00 F3 10 03 7C 32 FF` gesendet.

Daraufhin habe ich folgendes bekommen:

`FF 10 02 00 17 1F BE 08 08 05 03 05 1F E8 21 D4 41 1C DE D3 41 A8 EB D3 41 11 05 9F 41 60 CC BD 41 53 89 D1 41 08 00 54 42 1B 1B 43 42 52 38 DE C2 00 00 70 41 AF 78 95 41 5F 51 6B 41 F8 1F 7B 41 62 2B B7 41 00 00 A0 41 00 00 00 00 1C 26 D3 40 91 D9 1F 41 3A 33 BB 41 60 CC BD 41 11 05 9F 41 60 CC BD 41 1B 1B 43 42 31 16 12 0A 05 16 A4 1E C5 46 C0 3F 88 46 71 71 F4 45 55 9A 45 43 00 2D 0E 18 0A 05 07 2D 0E 18 0A 05 00 00 00 00 00 D7 9A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 13 DC 03 00 10 10 00 A0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40 08 08 00 00 00 00 00 00 00 01 2A 00 71 01 2A 00 28 35 9C 10 03 F5 F0 FF`

Vielen Dank

Gruß
Oliver

**Comment by mwllgr** [comment]
Hmmm, das sieht eigentlich richtig aus. Hast du es - rein zum Testen - schon einmal über FHEM oder im GUI-Modus des Programms probiert? Übrigens: Leider ist die Datei neue CSV-Datei von dir hier nicht angekommen. Sei so gut und lade die z. B. auf https://p.kll.li hoch und poste dann den Link hier. Danke!

**Comment by elektronikfreak** [comment]
Hallo,

 

ich habe das mit Hterm gemacht und FF 10 02 01 15 00 00 00 F3 10 03 7C 32 FF gesendet.

 

Daraufhin habe ich folgendes bekommen:

 

FF 10 02 00 17 1F BE 08 08 05 03 05 1F E8 21 D4 41 1C DE D3 41 A8 EB D3 41 11 05 9F 41 60 CC BD 41 53 89 D1 41 08 00 54 42 1B 1B 43 42 52 38 DE C2 00 00 70 41 AF 78 95 41 5F 51 6B 41 F8 1F 7B 41 62 2B B7 41 00 00 A0 41 00 00 00 00 1C 26 D3 40 91 D9 1F 41 3A 33 BB 41 60 CC BD 41 11 05 9F 41 60 CC BD 41 1B 1B 43 42 31 16 12 0A 05 16 A4 1E C5 46 C0 3F 88 46 71 71 F4 45 55 9A 45 43 00 2D 0E 18 0A 05 07 2D 0E 18 0A 05 00 00 00 00 00 D7 9A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 13 DC 03 00 10 10 00 A0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40 08 08 00 00 00 00 00 00 00 01 2A 00 71 01 2A 00 28 35 9C 10 03 F5 F0 FF

 

Vielen Dank

 

Gruß

Oliver

 

 

Von: mwllgr <> 
Gesendet: Mittwoch, 4. Mai 2022 20:35
An: mwllgr/java-wtkcontrol ***@***.***>
Cc: elektronikfreak ***@***.***>; Mention ***@***.***>
Betreff: Re: [mwllgr/java-wtkcontrol] Resuemat Version 8126 (Issue #1)

 

Hallo Oliver,
hast du schon versucht, Befehle manuell an die Heizung zu senden, um zu sehen, welche Bytes als Antwort zurückkommen? Das Programm wartet nur, wenn keine richtige Antwort gemeldet wird.

Sei so gut und probier mal, manuell einen Lesebefehl (z.B. über PuTTY) zu senden und die erhaltenen Bytes hier rein zu schreiben.

**Comment by mwllgr** [comment]
Thread wird aufgrund von Inaktivität und gelöschtem Account geschlossen.
